export const titles = [
  { id: "f", letter: "F" },
  { id: "u", letter: "u" },
  { id: "l", letter: "l" },
  { id: "l", letter: "l" },
  { id: "dash", letter: "-" },
  { id: "s", letter: "s" },
  { id: "t", letter: "t" },
  { id: "a3", letter: "a" },
  { id: "c", letter: "c" },
  { id: "k", letter: "k" },
  { id: "w", letter: "w" },
  { id: "e", letter: "e" },
  { id: "b", letter: "b" },
  { id: "d", letter: "d" },
  { id: "e", letter: "e" },
  { id: "v", letter: "v" },
  { id: "e", letter: "e" },
  { id: "l", letter: "l" },
  { id: "o", letter: "o" },
  { id: "p", letter: "p" },
  { id: "e", letter: "e" },
  { id: "r", letter: "r" },
];
